version: "3"
services:
  elasticsearch:
    env_file:
      - env_file.env
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - webnet
      
  kibana:
    env_file:
      - env_file.env
    image: docker.elastic.co/kibana/kibana:7.3.0
    ports:
      - 5601:5601
    networks:
      - webnet
    depends_on:
      - "elasticsearch" 
    
    
networks:
  webnet: