spring:
  application:
    name: cable-service
  zipkin:
    base-url: http://localhost:9412/
  sleuth:
    sampler:
      probability: 1
       
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
