version: "3"
services:
  cable:
    env_file:
      - env_file.env
    # replace username/repo:tag with your name and image details
    image: 7353207901/cable-service:1.0.1
    environment:
      - SPRING_PROFILES_ACTIVE:stg,jpa
      - GOOGLE_APPLICATION_CREDENTIALS:'/app/smartcableapp-211915-af70f90f4962.json'
   # deploy:
    # replicas: 2
      #resources:
       # limits:
       #   cpus: "0.1"
        #  memory: 50M
      #restart_policy:
      #  condition: on-failure
    ports:
      - 9082:8082
    networks:
      - webnet
    #command: --spring.profiles.active=dev,jpa
  user:
    env_file:
      - env_file.env
    image: 7353207901/user-service:1.0.1
    ports:
      - 8081:8081
    networks:
      - webnet
  config:
    env_file:
      - env_file.env
    image: 7353207901/config-service:1.0
    ports:
      - 9999:9999
    networks:
      - webnet
  zuul:
    env_file:
      - env_file.env
    image: 7353207901/zuul-service:1.0
    ports:
      - 8000:8000
    networks:
      - webnet
  eureka:
    env_file:
      - env_file.env
    image: 7353207901/eureka-service:1.0
    ports:
      - 8761:8761
    networks:
      - webnet
    
networks:
  webnet: