mgb:
    stringProp1: propValue1
    stringProp2: propValue2
    intProp1: 10
    listProp:
        - listValue1
        - listValue2
    usersMap:
        9980663789: agb123,ADMIN,Anand Badiger,1
        9164261146: gmb123,ADMIN,Gurunath Badiger,1
        7353207901: pmounesh,ADMIN,mounesh,2
       
sc:
  oauth:
    redirectURI: http://localhost:8083
    aTokenValidity: 604800
    rTokenValidity: 2592000
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
#spring:
  #datasource:
     # url: jdbc:mysql://google/kng_prod?cloudSqlInstance=smartcableapp-211915:asia-south1:smartcable&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
     # username: root
     # password: mgbKng123
  #jpa:
    #hibernate:
      #ddl-auto: update
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
spring: 
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    data:
        mongodb:
            uri: mongodb+srv://root:mgbKng123@cluster0-2xmkr.mongodb.net/test?retryWrites=true&w=majority
            database: trendfly_dev
