mgb:
    stringProp1: propValue1
    stringProp2: propValue2
    intProp1: 10
    listProp:
        - listValue1
        - listValue2
    usersMap:
        9980663789: panand,ADMIN,anandu,1
        7353207901: pmounesh,ADMIN,mounesh,2
       
sc:
  oauth:
    redirectURI: http://localhost:8083
    aTokenValidity: 60000
    rTokenValidity: 60000
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
    
spring:
  datasource:
      url: jdbc:mysql://google/mgb_kng?cloudSqlInstance=smartcableapp-211915:asia-south1:smartcable&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=mgb&password=mgb&useSSL=false
      username: root
      password: mgbKng123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
