version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: 7353207901/cable-service:1.0.1
    deploy:
      replicas: 5
      #resources:
       # limits:
       #   cpus: "0.1"
        #  memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8082"
    networks:
      - webnet
networks:
  webnet:
