apiVersion: v1
kind: Service
metadata:
  name: cable-service
  labels:
    app: cable-service
    role: api
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8082
  selector:
    app: cable-service
    role: api
    tier: backend
