apiVersion: v1
kind: Service
metadata:
  name: smart-ang-app
  labels:
    app: smart-ang-app
    role: ui
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: smart-ang-app
    role: ui
    tier: frontend
