apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: user-service
        role: api
        tier: backend
    spec:
      containers:
      - name: master
        image: docker.io/7353207901/user-service:1.0  # or just image: redis
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /app/smartcableapp-211915-af70f90f4962.json
        - name: SPRING_PROFILES_ACTIVE
          value: dev,jpa
        ports:
        - containerPort: 8081
