apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
    role: api
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: user-service
    role: api
    tier: backend
