apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
    role: api
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: eureka-service
    role: discovery
    tier: backend
