apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smart-ang-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: smart-ang-app
        role: ui
        tier: frontend
    spec:
      containers:
      - name: master
        image: docker.io/7353207901/smart-ang-app:1.1  # or just image: redis
        ports:
        - containerPort: 80
